# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0002_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grumbler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, default=20)),
                ('bio', models.CharField(blank=True, default='', max_length=420)),
                ('picture', models.ImageField(blank=True, upload_to='photos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=42),
        ),
    ]
