# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_auto_20171006_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='grumbler',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
